# Generated by Django 5.2.4 on 2025-08-24 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_branchoffice_department_organizationprofile_unit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="branchoffice",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="branchoffice",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organizationprofile",
            name="location_lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organizationprofile",
            name="location_lng",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
