# Generated by Django 4.2.23 on 2025-08-25 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_branchoffice_latitude_branchoffice_longitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="branchoffice",
            name="admin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_branches",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="branchoffice",
            name="admin_staff_id",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="corpmember",
            name="account",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="corper_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="corpmember",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="organizationuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("ORG", "Organization"),
                    ("BRANCH", "Branch Admin"),
                    ("CORPER", "Corper"),
                ],
                default="ORG",
                max_length=10,
            ),
        ),
    ]
