# Generated by Django 4.2.23 on 2025-08-25 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_branchoffice_admin_branchoffice_admin_staff_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="corpmember",
            name="face_encoding",
            field=models.TextField(blank=True, null=True),
        ),
    ]
