# Generated by Django 4.2.23 on 2025-08-25 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_remove_notification_scope_notification_created_by_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="publicholiday",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="publicholiday",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="publicholiday",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="publicholiday",
            unique_together={("user", "start_date", "end_date")},
        ),
        migrations.RemoveField(
            model_name="publicholiday",
            name="date",
        ),
    ]
