# Generated by Django 5.2.8 on 2025-11-24 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_systemsetting"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemsetting",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
