# Generated by Django 5.2.8 on 2026-05-13 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0023_nationalholiday"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="tempfaceencoding",
            new_name="accounts_te_corper__a77caf_idx",
            old_name="accounts_te_corper__eb1f35_idx",
        ),
    ]
