# Generated by Codex

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_queryrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='queryrecord',
            name='corper_reply',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='queryrecord',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='queryrecord',
            name='replied_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='query_replies',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]

