# Generated by Codex

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def seed_subscription_plans(apps, schema_editor):
    Plan = apps.get_model('accounts', 'SubscriptionPlanSetting')
    defaults = [
        ('STARTER', {
            'name': 'Starter',
            'corper_min': 0,
            'corper_max': 10,
            'monthly_price': Decimal('0.00'),
            'yearly_price': Decimal('0.00'),
            'sort_order': 1,
        }),
        ('BASIC', {
            'name': 'Basic',
            'corper_min': 10,
            'corper_max': 50,
            'monthly_price': Decimal('25000.00'),
            'yearly_price': Decimal('258000.00'),
            'sort_order': 2,
        }),
        ('PRO', {
            'name': 'Pro',
            'corper_min': 50,
            'corper_max': 100,
            'monthly_price': Decimal('45000.00'),
            'yearly_price': Decimal('510000.00'),
            'sort_order': 3,
        }),
        ('ENTERPRISE', {
            'name': 'Enterprise',
            'corper_min': 100,
            'corper_max': None,
            'monthly_price': Decimal('95000.00'),
            'yearly_price': Decimal('999999.00'),
            'sort_order': 4,
        }),
    ]
    for code, plan_defaults in defaults:
        Plan.objects.update_or_create(code=code, defaults=plan_defaults)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_queryrecord_reply_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlanSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('STARTER', 'Starter'), ('BASIC', 'Basic'), ('PRO', 'Pro'), ('ENTERPRISE', 'Enterprise')], max_length=20, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('corper_min', models.PositiveIntegerField(default=0)),
                ('corper_max', models.PositiveIntegerField(blank=True, null=True)),
                ('monthly_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('yearly_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('discount_enabled', models.BooleanField(default=False)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subscription Plan Setting',
                'verbose_name_plural': 'Subscription Plan Settings',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='OrganizationSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_code', models.CharField(max_length=20)),
                ('plan_name', models.CharField(max_length=80)),
                ('billing_cycle', models.CharField(choices=[('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], default='MONTHLY', max_length=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('starts_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='accounts.subscriptionplansetting')),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_code', models.CharField(max_length=20)),
                ('plan_name', models.CharField(max_length=80)),
                ('billing_cycle', models.CharField(choices=[('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], default='MONTHLY', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('amount_charged', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_payments', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='accounts.subscriptionplansetting')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.RunPython(seed_subscription_plans, reverse_code=migrations.RunPython.noop),
    ]
