# Generated by Codex

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_subscription_plans'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClearanceAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=64, unique=True)),
                ('year_month', models.CharField(db_index=True, max_length=6)),
                ('source', models.CharField(choices=[('SUBSCRIPTION', 'Subscription'), ('ORG_WALLET', 'Organization Wallet'), ('BRANCH_WALLET', 'Admin Wallet'), ('CORPER_WALLET', 'Corper Wallet'), ('EXISTING_WALLET_CHARGE', 'Existing Wallet Charge')], max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clearance_accesses', to='accounts.branchoffice')),
                ('corper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clearance_accesses', to='accounts.corpmember')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clearance_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Clearance Access',
                'verbose_name_plural': 'Clearance Accesses',
                'ordering': ('-created_at', '-id'),
                'unique_together': {('corper', 'year_month')},
            },
        ),
    ]
