# Generated by Codex

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_clearanceaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='auth_token_version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
