# Generated by Codex

from decimal import Decimal

from django.db import migrations


def update_starter_plan_price(apps, schema_editor):
    Plan = apps.get_model('accounts', 'SubscriptionPlanSetting')
    Plan.objects.filter(code='STARTER').update(
        monthly_price=Decimal('5000.00'),
        yearly_price=Decimal('55000.00'),
    )


def restore_starter_plan_free(apps, schema_editor):
    Plan = apps.get_model('accounts', 'SubscriptionPlanSetting')
    Plan.objects.filter(code='STARTER').update(
        monthly_price=Decimal('0.00'),
        yearly_price=Decimal('0.00'),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_systemsetting_auth_token_version'),
    ]

    operations = [
        migrations.RunPython(update_starter_plan_price, restore_starter_plan_free),
    ]
