# Generated by Codex

from django.db import migrations


def rename_pro_to_premium(apps, schema_editor):
    Plan = apps.get_model('accounts', 'SubscriptionPlanSetting')
    Subscription = apps.get_model('accounts', 'OrganizationSubscription')
    Payment = apps.get_model('accounts', 'SubscriptionPayment')
    Plan.objects.filter(code='PRO').update(name='Premium')
    Subscription.objects.filter(plan_code='PRO').update(plan_name='Premium')
    Payment.objects.filter(plan_code='PRO').update(plan_name='Premium')


def rename_premium_to_pro(apps, schema_editor):
    Plan = apps.get_model('accounts', 'SubscriptionPlanSetting')
    Subscription = apps.get_model('accounts', 'OrganizationSubscription')
    Payment = apps.get_model('accounts', 'SubscriptionPayment')
    Plan.objects.filter(code='PRO').update(name='Pro')
    Subscription.objects.filter(plan_code='PRO').update(plan_name='Pro')
    Payment.objects.filter(plan_code='PRO').update(plan_name='Pro')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_update_starter_plan_price'),
    ]

    operations = [
        migrations.RunPython(rename_pro_to_premium, rename_premium_to_pro),
    ]
