# Generated by Codex

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_rename_pro_plan_to_premium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationprofile',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='org_logos/'),
        ),
    ]
