# Generated by Django 5.2.8 on 2026-05-18 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0033_alter_organizationprofile_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptionplansetting",
            name="code",
            field=models.CharField(
                choices=[
                    ("STARTER", "Starter"),
                    ("BASIC", "Basic"),
                    ("PRO", "Premium"),
                    ("ENTERPRISE", "Enterprise"),
                ],
                max_length=20,
                unique=True,
            ),
        ),
    ]
