# Generated by Codex on 2026-05-18

from django.conf import settings
from django.db import migrations, models


def forwards(apps, schema_editor):
    Department = apps.get_model("accounts", "Department")
    BranchOffice = apps.get_model("accounts", "BranchOffice")

    # Migrate existing department.branch into department.user + department.branches
    for dept in Department.objects.select_related("branch").all():
        branch = getattr(dept, "branch", None)
        if not branch:
            continue
        dept.user_id = branch.user_id
        dept.save(update_fields=["user"])
        try:
            dept.branches.add(branch)
        except Exception:
            pass


def backwards(apps, schema_editor):
    Department = apps.get_model("accounts", "Department")
    # Best-effort restore department.branch using the first related branch if present
    for dept in Department.objects.all():
        try:
            first = dept.branches.first()
        except Exception:
            first = None
        if first:
            dept.branch_id = first.id
            dept.save(update_fields=["branch"])


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0034_alter_subscriptionplansetting_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="user",
            field=models.ForeignKey(
                on_delete=models.deletion.CASCADE,
                related_name="departments",
                to=settings.AUTH_USER_MODEL,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="branches",
            field=models.ManyToManyField(blank=True, related_name="departments", to="accounts.branchoffice"),
        ),
        migrations.RunPython(forwards, backwards),
        migrations.AlterField(
            model_name="department",
            name="user",
            field=models.ForeignKey(
                on_delete=models.deletion.CASCADE,
                related_name="departments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RemoveField(
            model_name="department",
            name="branch",
        ),
    ]

