# Generated by Codex on 2026-05-18

from django.conf import settings
from django.db import migrations, models


def forwards(apps, schema_editor):
    Unit = apps.get_model("accounts", "Unit")
    Department = apps.get_model("accounts", "Department")

    # Backfill Unit.user from Unit.department.user when present.
    for unit in Unit.objects.select_related("department").all():
        dept = getattr(unit, "department", None)
        if dept and getattr(dept, "user_id", None):
            unit.user_id = dept.user_id
            unit.save(update_fields=["user"])


def backwards(apps, schema_editor):
    Unit = apps.get_model("accounts", "Unit")
    Department = apps.get_model("accounts", "Department")

    # Best-effort restore Unit.department from any matching department name in the org.
    for unit in Unit.objects.all():
        if getattr(unit, "department_id", None):
            continue
        dept = Department.objects.filter(user_id=unit.user_id).order_by("id").first()
        if dept:
            unit.department_id = dept.id
            unit.save(update_fields=["department"])


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0035_department_user_branches"),
    ]

    operations = [
        migrations.AddField(
            model_name="unit",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=models.deletion.CASCADE,
                related_name="units",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(forwards, backwards),
        migrations.AlterField(
            model_name="unit",
            name="user",
            field=models.ForeignKey(
                on_delete=models.deletion.CASCADE,
                related_name="units",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RemoveField(
            model_name="unit",
            name="department",
        ),
        migrations.RemoveField(
            model_name="department",
            name="branches",
        ),
    ]

